<a href="https://colab.research.google.com/github/Ram-potadar/Data-Analytics/blob/main/numpyLession.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [ ]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [ ]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

to add more we end up with a many variables so to avoide that what we can do here is by creating vector for the each input like below

In [ ]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [ ]:
weights = [w1, w2, w3]

In [ ]:
for x, y in zip(kanto, weights):
  print(x)
  print(y)


73
0.3
67
0.2
43
0.5


We can now write a function `crop_yield` to calcuate the yield of apples (or any other crop) given the climate data and the respective weights.

In [ ]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [ ]:
crop_yield(kanto, weights)

56.8

In [ ]:
crop_yield(johto, weights)


76.9

In [ ]:
crop_yield(hoenn, weights)


81.9

In [ ]:
crop_yield(sinnoh, weights)


57.699999999999996

the above calculation is also called as the dot product

The Numpy library provides a built-in function to compute the dot product of two vectors

In [ ]:
import numpy as np


Numpy arrays can be created by using numpy.array function


In [ ]:
kanto = np.array([73, 67, 43])

In [ ]:
kanto

array([73, 67, 43])

In [ ]:
weights = np.array([w1, w2, w3])

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
type(weights)

numpy.ndarray

In [ ]:

weights[0]

0.3

### Operations on Numpy Arrays

Now we can compute the dot product by using np.dot function

In [ ]:
np.dot(kanto, weights )

56.8

We can also perform the element wise operations as below

In [ ]:
(kanto * weights ).sum()

56.8

the * operator is ussed to element wise multiplication of two numpy array it they have the same size. And + operator is used to add 2 numpy arrays


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:

arr3 = arr1 * arr2

In [ ]:
(arr1 * arr2 ).sum()

32

In [ ]:
arr1 + arr2

array([5, 7, 9])

## Benefits of using Numpy arrays

Numpy arrays offer the following benefits over Python lists for operating on numerical data:

- **Ease of use**: You can write small, concise, and intuitive mathematical expressions like `(kanto * weights).sum()` rather than using loops & custom functions like `crop_yield`.
- **Performance**: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops that are interpreted at runtime




In [ ]:
arr1 =  list(range(1000000))
arr2 =  list(range(1000000, 2000000))

In [ ]:
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1 , x2 in zip(arr1, arr2):
  result += x1 * x2
result

CPU times: user 375 ms, sys: 8.67 ms, total: 383 ms
Wall time: 732 ms


833332333333500000

In [ ]:
np.dot(arr1_np, arr2_np)

833332333333500000

In [ ]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 2 ms, sys: 4 µs, total: 2.01 ms
Wall time: 7.03 ms


833332333333500000

# Multi-Dimentional Numpy arrays

In [ ]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [ ]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

If you've taken a linear algebra class in high school, you may recognize the above 2-d array as a matrix with five rows and three columns. Each row represents one region, and the columns represent temperature, rainfall, and humidity, respectively.

Numpy arrays can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of an array.

<!-- <img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="420"> -->


We can insepect the length along each dimension using the .shape property of an array

In [ ]:
#2D array
climate_data.shape

(5, 3)

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
weights.shape

(3,)

In [ ]:
# 3D array
arr3 = np.array([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.5]]])

In [ ]:
arr3

array([[[11. , 12. , 13. ],
        [13. , 14. , 15. ]],

       [[15. , 16. , 17. ],
        [17. , 18. , 19.5]]])

In [ ]:
arr3.shape

(2, 2, 3)

All the elements in a numpy array have the same data type. You can check the data type of an array using the `.dtype` property.

In [ ]:
weights.dtype

dtype('float64')

In [ ]:
arr3.dtype

dtype('float64')

In [ ]:
climate_data.dtype

dtype('int64')

In [ ]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
weights

array([0.3, 0.2, 0.5])

np.matmul function or the @ operator to perform the matrix multiplication.

In [ ]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

# Working with CSV data files

Numpy also provides helper functions reading from & writing to files. Let's download a file climate.txt, which contains 10,000 climate measurements (temperature, rainfall & humidity) in the following format:


CSVs: A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas.

In [ ]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f1f480bf760>)

In [ ]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [ ]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [ ]:
climate_data.shape


(10000, 3)

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
yields = climate_data @ weights

In [ ]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [ ]:
yields.shape

(10000,)

Let's add the `yields` to `climate_data` as a fourth column using the [`np.concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) function.

In [ ]:
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)), axis = 1)

In [ ]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [ ]:
np.savetxt('climate_results.txt',
           climate_results,
           fmt='%.2f',
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples',
           comments='')



*   Mathematics: np.sum, np.exp, np.round, arithemtic operators

*   Array manipulation: np.reshape, np.stack, np.concatenate, np.split


*   Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals

*   Statistics: np.mean, np.median, np.std, np.max










## Arithmetic operations, broadcasting and comparison

Numpy arrays support arithmetic operators like `+`, `-`, `*`, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays.

In [ ]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

In [ ]:
arr3 = np.array([[11, 12, 13, 14],
                 [15, 16, 17, 18],
                 [19, 11, 12, 13]])

In [ ]:
arr2 + arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [ ]:
#Adding scalar

arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [ ]:
arr2 - arr3

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [ ]:
# Division by scalar
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [ ]:
# Element-wise multiplication
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [ ]:
# Modulus with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

### Array Broadcasting

Numpy arrays also support *broadcasting*, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works.


In [ ]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr4 = np.array([4, 5, 6, 7])

In [ ]:
arr4.shape

(4,)

In [ ]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

When the expression `arr2 + arr4` is evaluated, `arr4` (which has the shape `(4,)`) is replicated three times to match the shape `(3, 4)` of `arr2`. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

Broadcasting only works if one of the arrays can be replicated to match the other array's shape.

In [ ]:
arr5 = np.array([7, 8])

In [ ]:
arr5.shape

(2,)

In [ ]:
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [ ]:
arr5

array([7, 8])

In [ ]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [ ]:
arr1 = np.array([[1,2,3], [3,4,5]])
arr2 = np.array([[1,2,3], [1,2,5]])

In [ ]:
arr1 == arr2

In [ ]:
arr2 != arr1

In [ ]:
arr1 >= arr2

In [ ]:
arr2 < arr1

In [ ]:
(arr1 == arr2).sum()

## Array indexing and slicing

Numpy extends Python's list indexing notation using [ ] to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

In [ ]:

arr3 = np.array([
    [[11,12,13,14],
     [13,14,15,19]],

    [[15,16,17,21],
     [63,92,36,18]],

    [[98,32,81,23],
     [17,18,19.5,43]]])

In [ ]:
arr3.shape

In [ ]:
#Single element
arr3[1,1,2]

In [ ]:
#Subarray using ranges
arr3[1:,0:1,:2]

In [ ]:
arr3[1]

In [ ]:
arr3[1:]

In [ ]:
arr3[1:, 0:1]

In [ ]:
arr3[1:, 0:1, 0:2]

In [ ]:
arr3[2:, 1, 1]

## Other ways of creating Numpy arrays

Numpy also provides some handy functions to create arrays of desired shapes with fixed or random values. Check out the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function to learn more.

In [ ]:
#All zeros
np.zeros((3,2))

In [ ]:
#All ones
np.ones([2,2 ,2])

In [ ]:
#Identity matrix
np.eye(3)

In [ ]:
#Random vecotor
np.random.rand(5)

In [ ]:
np.random.randn(2,3)

In [ ]:
#fixed value
arr_full = np.full([2,3],42)
arr_full

In [ ]:
# Range with start, end and step
np.arange(10, 90, 3)


In [ ]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

# 100 numpy exercises!!

In [ ]:
import numpy as np

In [ ]:
np.zeros(10)

In [ ]:
arr1 = np.array([[[1,2,3],
                 [3,4,5]],
                 [[4,5,6],
                  [5,6,7]]])

In [ ]:
arr1

In [ ]:
arr1.shape

In [ ]:
 x,y,z = arr1.shape

In [ ]:
x

In [ ]:
y

In [ ]:
3

In [ ]:
arr1.dtype